version: '3.8'
services:
  backend:
    build:
      context:  .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:app
    depends_on:
      - db


  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DATABASE: admin
      POSTGRES_USER: george
      POSTGRES_PASSWORD: glokgun166
    volumes:
      - .dbdata:/var/lib/postgres

