version: '3.8'
services:
  backend:
    build:
      context:  .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:app
    depends_on:
      - db


  db:
    image: postgres:9.10.2
    restart: always
    environment:
      POSTGRES_DATABASE: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - 33066:3306

